CREATE DATABASE HEALTHSYNC;

USE HEALTHSYNC;

CREATE TABLE USER (
    CDUSER INT AUTO_INCREMENT PRIMARY KEY,
    NMUSER VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CELLPHONE INT,
    PASSWORD VARCHAR(30) NOT NULL
);

CREATE TABLE USERHEALTH (
    CDUSERHEALTH INT AUTO_INCREMENT PRIMARY KEY,
    CDUSER INT NOT NULL,
    VLTYPE INT NOT NULL,
    FGTYPE INT NOT NULL,
    DTHEALTH DATETIME NOT NULL,
    FOREIGN KEY (CDUSER) REFERENCES USER(CDUSER)
);

CREATE TABLE PERMISSION (
    CDPERMISSION INT AUTO_INCREMENT PRIMARY KEY,
    IDPERMISSION INT NOT NULL
);

CREATE TABLE USERPERMISSION (
    CDUSERPERMISSION INT AUTO_INCREMENT PRIMARY KEY,
    CDUSER INT,
    CDPERMISSION INT,
    FOREIGN KEY (CDUSER) REFERENCES USER(CDUSER),
    FOREIGN KEY (CDPERMISSION) REFERENCES PERMISSION(CDPERMISSION)
);

CREATE TABLE CATEGORY (
    CDCATEGORY INT AUTO_INCREMENT PRIMARY KEY,
    NMCATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE MEDICATION (
    CDMEDICATION INT AUTO_INCREMENT PRIMARY KEY,
    NMMEDICATION VARCHAR(255) NOT NULL,
    CDCATEGORY INT,
    FOREIGN KEY (CDCATEGORY) REFERENCES CATEGORY(CDCATEGORY)
);

CREATE TABLE COURSE (
    CDCOURSE INT AUTO_INCREMENT PRIMARY KEY,
    NMCOURSE VARCHAR(500) NOT NULL,
    CONTENT VARCHAR(4000)
);

CREATE TABLE COMMENT (
    CDCOMMENT INT AUTO_INCREMENT PRIMARY KEY,
    DSCOMMENT VARCHAR(255) NOT NULL,
    CDCOURSE INT,
    CDUSER INT,
    FOREIGN KEY (CDUSER) REFERENCES USER(CDUSER),
    FOREIGN KEY (CDCOURSE) REFERENCES COURSE(CDCOURSE)
);

CREATE TABLE AVALIATION (
    CDAVALIATION INT AUTO_INCREMENT PRIMARY KEY,
    DSAVALIATION VARCHAR(2000) NOT NULL,
    CDCOURSE INT,
    FOREIGN KEY (CDCOURSE) REFERENCES COURSE(CDCOURSE)
);

CREATE TABLE ROUTINE (
    CDROUTINE INT AUTO_INCREMENT PRIMARY KEY,
    CDUSER INT NOT NULL,
    CDMEDICATION INT NOT NULL,
    DTSTART DATETIME NOT NULL,
    DTFINISH DATE,
    FREQUENCY INT NOT NULL,
    FOREIGN KEY (CDUSER) REFERENCES USER(CDUSER),
    FOREIGN KEY (CDMEDICATION) REFERENCES MEDICATION(CDMEDICATION)
);

CREATE TABLE ROUTINEREGISTER (
    CDROUTINEREGISTER INT AUTO_INCREMENT PRIMARY KEY,
    CDROUTINE INT,
    DTREAL DATETIME,
    DTEXPECTED DATETIME NOT NULL,
    FGTYPE INT NOT NULL,
    FOREIGN KEY (CDROUTINE) REFERENCES ROUTINE(CDROUTINE)
);

CREATE TABLE HISTORY (
    CDHISTORY INT AUTO_INCREMENT PRIMARY KEY,
    CDROUTINEREGISTER INT NOT NULL,
    MSGCONTENT VARCHAR(4000),
    FOREIGN KEY (CDROUTINEREGISTER) REFERENCES ROUTINEREGISTER(CDROUTINEREGISTER)
);